### ISSUE TITLE
Implement BLPOP functionality

### ISSUE THREAD

**Issue by jdrago999** [yongman/tidis#1]
Excellent project!

I'm currently using LedisDB [1] in my Golang project, but would prefer to have a 100% Golang option.

What are your thoughts on implementing BLPOP functionality in `tidis`?

[1] https://github.com/siddontang/ledisdb

Edit: Added link to LedisDB

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
