### ISSUE TITLE
can keys be stored in memory ?

### ISSUE THREAD

**Issue by carr123** [yongman/tidis#16]
I wander if keys can be stored in memory, and have 2 or 3 replicas across nodes.
i don't need data persistence, i don't have expensive ssd disk. i just need speed and survive one node crash.
if could, how ?

**Comment by yongman** [comment]
No, it can't.

`Tidis` use `tikv` as backend storage, served by `RocksDB`. `RocksDB` is just a disk key value storage and provide good performance for write.

If you want store all data in memory or care about the performance, just use `redis` or `redis cluster`, which will have excellent performance.

`Tidis` is  located in the scenario where a large amount of data and not extremely sensitive with the latency.

**Comment by yongman** [comment]
For now, close this issue.
