### ISSUE TITLE
CPU 占用太高

### ISSUE THREAD

**Issue by carr123** [yongman/tidis#17]
我开了2个tikv 节点。
在set了1000个key之后客户端就退出了。 每个key的过期时间是10秒。
然后其中一个节点上的tikv-server CPU占用  >80%，长时间居高不下，另一个节点tikv-server 几乎不耗CPU。

哪里出问题了？

**Comment by yongman** [comment]
由于数据过期是另外的任务周期性的check，涉及到创建Iterator，大量过期的key清理会占用大量资源。

不过可以调整`string_checker_loop`和`string_checker_interval`的值来加快淘汰过程。

**Comment by yongman** [comment]
lazy ttl check is wip, string type already implemented.
