### ISSUE TITLE
Any documentation on transaction support

### ISSUE THREAD

**Issue by rohitjoshi** [yongman/tidis#18]
I have a use-case where two key-val should be inserted atomically (if not exist)and either insert fails should roll back.  The 2nd key is a secondary index.

Key1= Hash1
Value1= Token1

Key2= Token1
Value2= json payload

How can I insert both atomically?  Now if  Key1 or Key2 (Token1) already exists, it should roll back the operation.

I see [`HmsetWithTxn` ](https://github.com/yongman/tidis/blob/master/tidis/t_hash.go#L380) but would like to see support for `HmsetnxWithTxn` which allows insertion of multiple keys if don't exist in a transaction.

**Comment by yongman** [comment]
Just use  multi and exec commands to have transaction support.

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
