### ISSUE TITLE
Hello from TiKV

### ISSUE THREAD

**Issue by siddontang** [yongman/tidis#3]
Hi @yongman 

I am very glad to see this project, do you meet any problem? If yes, please tell me. 
It is very appreciated that you can give me your Wechat or email, and we can have a deep discussion later.

Thank you!

**Comment by yongman** [comment]
Thanks to your attention. This project is now work in process and doing in my amateur time, and I study a lot from your ledisdb project. 

I am glad to have your support during this process and this is my email `yming0221#gmail.com`
