### ISSUE TITLE
runtest failed 4 test cases

### ISSUE THREAD

**Issue by benamazing** [yongman/tidis#36]
`
======================================================================
FAIL: test_expire (test_string.StringTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk/ssd/tidis/tests/test_string.py", line 165, in test_expire
    self.assertIsNone(self.r.get(self.k1))
AssertionError: 'value1' is not None

======================================================================
FAIL: test_expireat (test_string.StringTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk/ssd/tidis/tests/test_string.py", line 175, in test_expireat
    self.assertIsNone(self.r.get(self.k1))
AssertionError: 'value1' is not None

======================================================================
FAIL: test_pexpire (test_string.StringTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk/ssd/tidis/tests/test_string.py", line 146, in test_pexpire
    self.assertIsNone(self.r.get(self.k1))
AssertionError: 'value1' is not None

======================================================================
FAIL: test_pexpireat (test_string.StringTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk/ssd/tidis/tests/test_string.py", line 156, in test_pexpireat
    self.assertIsNone(self.r.get(self.k1))
AssertionError: 'value1' is not None

----------------------------------------------------------------------
Ran 82 tests in 137.529s

FAILED (failures=4)
`

Hi, I just built tidis from latest source, and ran the runtest script, however, got 4 test cases failed as above, what might be the reason? Could be due to pd/tikv? Thanks.

**Comment by yongman** [comment]
Can you paste your configuration file?
I think you can set `ttl_checker_lazy = true` for string type and run test again.
Just as follows:
```
#expiration checker
string_checker_loop = 10
string_checker_interval = 100000

list_checker_loop = 10
list_checker_interval = 100000

hash_checker_loop = 10
hash_checker_interval = 100000

set_checker_loop = 10
set_checker_interval = 100000

zset_checker_loop = 10
zset_checker_interval = 100

ttl_checker_lazy = true
```

**Comment by benamazing** [comment]
oh, yes, it worked now after i changed ttl_checker_lazy to true, thanks~~
