### ISSUE TITLE
大神求助

### ISSUE THREAD

**Issue by zouyadong** [yongman/tidis#38]
测试发现 为什么 tidis 服务运行一段时间会自动结束呢

**Comment by zouyadong** [comment]
time="2018-11-15T09:34:51+08:00" level=warning msg="get timestamp too slow: 119.57324ms"
time="2018-11-15T09:34:51+08:00" level=warning msg="get timestamp too slow: 119.689305ms"
time="2018-11-15T09:34:51+08:00" level=warning msg="get timestamp too slow: 119.687875ms"
time="2018-11-15T09:34:55+08:00" level=warning msg="get timestamp too slow: 119.649037ms"
time="2018-11-15T09:34:55+08:00" level=warning msg="get timestamp too slow: 123.160555ms"
time="2018-11-15T09:34:55+08:00" level=warning msg="get timestamp too slow: 123.16436ms"
time="2018-11-15T09:34:55+08:00" level=warning msg="get timestamp too slow: 215.864347ms"
time="2018-11-15T09:34:55+08:00" level=warning msg="get timestamp too slow: 215.896503ms"
很多这样的日志

**Comment by zouyadong** [comment]
我再启动观察看看

**Comment by zouyadong** [comment]
这是我的启动命令
 nohup ./tidis-server -conf ../config.toml &
以下是启动成功的日志           
time="2018-11-20T21:59:15+08:00" level=info msg="server started"
time="2018-11-20T21:59:15+08:00" level=info msg="[pd] create pd client with endpoints [172.18.66.70:2379]"
time="2018-11-20T21:59:15+08:00" level=info msg="[pd] leader switches to: http://172.18.66.70:2379, previous: "
time="2018-11-20T21:59:15+08:00" level=info msg="[pd] init cluster id 6617753999325363518"
time="2018-11-20T21:59:15+08:00" level=info msg="server listen in :5379"
time="2018-11-20T21:59:15+08:00" level=info msg="Async tasks started for async deletion"

然后日志就不停的打印
time="2018-11-20T21:59:40+08:00" level=warning msg="get timestamp too slow: 115.140053ms"
time="2018-11-20T21:59:40+08:00" level=warning msg="get timestamp too slow: 116.52495ms"
time="2018-11-20T21:59:40+08:00" level=warning msg="get timestamp too slow: 116.540613ms"
time="2018-11-20T21:59:40+08:00" level=warning msg="get timestamp too slow: 116.640485ms"

**Comment by yongman** [comment]
@zouyadong this is normal, and the warning log is about your host is too slow to get timestamp to execute command transaction.

**Comment by zouyadong** [comment]
大神我想请教一下，tidis 可以用生产环境吗，有没有一些日常维护或设计文档 可以学习一下呀。他如何实现集群。还有个问题，能否分享一下tidis zset 的实现原理，以及性能如何，嘿嘿。

**Comment by jasonkoo** [comment]
@yongman I also have this warning  after I start tidis-server. Do you know how to avoid these warnings?

**Comment by sotowang** [comment]
> @yongman I also have this warning after I start tidis-server. Do you know how to avoid these warnings?

+1

**Comment by yongman** [comment]
> > @yongman I also have this warning after I start tidis-server. Do you know how to avoid these warnings?
> 
> +1

@sotowang this is normal case, and the warning log is about your host is too slow to get timestamp to execute command transaction.

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
