### ISSUE TITLE
Build Error: cannot find package

### ISSUE THREAD

**Issue by jasonkoo** [yongman/tidis#39]
Hi,
I am trying to build tidis with the `make` command.  I get the following error. Can you give me some help?

CGO_ENABLED=0 go build -o bin/tidis-server cmd/server/*
cmd/server/main.go:16:2: cannot find package "github.com/yongman/go/log" in any of:
	/usr/local/Cellar/go/1.11.2/libexec/src/github.com/yongman/go/log (from $GOROOT)
	/Users/lei.gu/go/src/github.com/yongman/go/log (from $GOPATH)
cmd/server/main.go:17:2: cannot find package "github.com/yongman/tidis/config" in any of:
	/usr/local/Cellar/go/1.11.2/libexec/src/github.com/yongman/tidis/config (from $GOROOT)
	/Users/lei.gu/go/src/github.com/yongman/tidis/config (from $GOPATH)
cmd/server/main.go:18:2: cannot find package "github.com/yongman/tidis/server" in any of:
	/usr/local/Cellar/go/1.11.2/libexec/src/github.com/yongman/tidis/server (from $GOROOT)
	/Users/lei.gu/go/src/github.com/yongman/tidis/server (from $GOPATH)
make: *** [build] Error 1

I saw three imports in `cmd/server/main.go`
"github.com/yongman/go/log"
"github.com/yongman/tidis/config"
"github.com/yongman/tidis/server"

where can I find these three dependencies?

**Comment by yongman** [comment]
all dependencies are located in vendor, you just need go get project to GOPATH and make.

**Comment by xujingbin** [comment]
![image](https://user-images.githubusercontent.com/22829724/52776398-6e881200-307c-11e9-877a-9a1cfa63be7c.png)
