### ISSUE TITLE
level=error msg="[pd] failed to get cluster id: rpc error: code = Unavailable desc = grpc: the connection is unavailable"

### ISSUE THREAD

**Issue by xujingbin** [yongman/tidis#41]

**Comment by yongman** [comment]
Please provide your config or you can use docker-compose to run tidis in one command.

**Comment by dinggel** [comment]
Use default configuration except PDS = "10.3.0.183:2379" to connect to the tidb cluster in use

**Comment by dinggel** [comment]
@yongman

**Comment by yongman** [comment]
@dinggel I am not sure your environment configuration, it seems to be network error.
Please setup a new tikv cluster in https://github.com/yongman/tidis/blob/master/README.md and retry to find out the problem.

**Comment by dinggel** [comment]
my tidb is build from https://www.pingcap.com/，Doesn't that work
