### ISSUE TITLE
Is tidis production ready?

### ISSUE THREAD

**Issue by xidianwlc** [yongman/tidis#48]
Is tidis production ready?
Do you use tidis in your compony ?

**Comment by yongman** [comment]
No, it is still in alpha and not production ready.
You can test tidis in offline env and open new issue if find bugs or make a pull request.

**Comment by tmikaeld** [comment]
Is it production read now? We'd like to use it in our company.

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
