### ISSUE TITLE
hclear lclear zclear bug

### ISSUE THREAD

**Issue by jklofs** [yongman/tidis#55]
hclear lclear zclear不支持多删除、 del和sclear可以支持多key删除

**Comment by yongman** [comment]
This is not bug, just not implemented yet. More work should be done to support it.
It will be helpful creating issues for future work. 
Thanks again.

**Comment by jklofs** [comment]
OK.In my tidis's client,I will implemente it.

**Comment by jklofs** [comment]
> This is not bug, just not implemented yet. More work should be done to support it.
> It will be helpful creating issues for future work.
> Thanks again.

OK.In my tidis's client,I will implemente it

**Comment by yongman** [comment]
Looking forward to your PRs. :-)

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
