### ISSUE TITLE
sort set bug

### ISSUE THREAD

**Issue by jklofs** [yongman/tidis#57]
sort set 在redis中的score值为浮点型，而在tidis中该值被限定为长整型

**Comment by jklofs** [comment]
zincrby  的返回值返回的是string类型的，因为分数的返回值是浮点型，当然这个和上述的问题是一致的

**Comment by jklofs** [comment]
@yongman

**Comment by yongman** [comment]
`Tidis` is not 100% compatible with `redis` API. 
The main reason is that float is more complexity to encode/decode to key in tikv, and user could convert float to int in service logic.
