### ISSUE TITLE
sort set withscores bug

### ISSUE THREAD

**Issue by jklofs** [yongman/tidis#59]
当执行时
```
zrangebyscore dss 0 0 withscores limit 0 2999
```
返回空值，可是空值的返回码和redis的不一致
redis的为：
![image](https://user-images.githubusercontent.com/24784965/53460945-e4777a80-3a79-11e9-8fcb-6e13714d8251.png)
而tidis中为
![image](https://user-images.githubusercontent.com/24784965/53460960-f0fbd300-3a79-11e9-92fb-b0a681f36baf.png)

**Comment by yongman** [comment]
Can you provide more data for reproduction?

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
