### ISSUE TITLE
tidis optimize to delete big key later ?  

### ISSUE THREAD

**Issue by rfyiamcool** [yongman/tidis#6]
I thank tidis delete big key, it is slow . example, delete a 100w items hash data.
thank you .

**Comment by yongman** [comment]
Yeah, this feature will be added later.
And one way to implement this is add extern version to a key encoding, so we can act same as all items keys actually deleted when we add it to a background job queue.

**Comment by yongman** [comment]
lazy deletion implemented on branch master, just use a simple way.

If a big key being deleted, tidis just mark the key deleted in the meta, and notify a async task to delete the big key in a sync way. 

During the key sync deletion, any read request will return `nil`, and any write command will be receive a ERR named `BUSYKEY key is deleting, retry later`.
