### ISSUE TITLE
Lazy delete ttl=0

### ISSUE THREAD

**Issue by jklofs** [yongman/tidis#60]
懒删除没有生效，ttl=0时,在轮询删除没有轮询到时，还是可以查到值
```
172.16.1.32:0>set dssvalue1 dsada EX 1
"OK"

172.16.1.32:0>set dssvalue1 dsada EX 1
"OK"

172.16.1.32:0>ttl dssvalue1
"0"

172.16.1.32:0>get dssvalue1
"dsada"
```

**Comment by yongman** [comment]
You can set `string_checker_interval` lower ( 10? )to check ttl in background quickly.
In your case, `ttl` will not trigger a lazy deletion, but `get` will do, please make sure `ttl_checker_lazy` is set to `true`.

**Comment by jklofs** [comment]
Thanks
