### ISSUE TITLE
sinter/sdiff/sunion/sunionstore/sdiffstore/sinterstore bug

### ISSUE THREAD

**Issue by jklofs** [yongman/tidis#61]
sinter/sdiff/sunion/sunionstore/sdiffstore/sinterstore当传入的set的key出现空值时会抛异常
```
sinter dssSet3 dssSet2
```
![image](https://user-images.githubusercontent.com/24784965/53552091-8f209380-3b75-11e9-8bac-73e4e2e0aa54.png)

**Comment by yongman** [comment]
Already fixed. Thanks.

**Comment by jklofs** [comment]
测试了下载redis的client中执行还是会出现那个报错

**Comment by jklofs** [comment]
![image](https://user-images.githubusercontent.com/24784965/53722012-7d096280-3e9f-11e9-8034-de115da84735.png)

**Comment by jklofs** [comment]
其中sdiff已经修复
![image](https://user-images.githubusercontent.com/24784965/53722110-bfcb3a80-3e9f-11e9-8a56-3b51e951f93c.png)

**Comment by jklofs** [comment]
sunionstore/sdiffstore/sinterstore 都有问题
![image](https://user-images.githubusercontent.com/24784965/53722295-2b150c80-3ea0-11e9-9050-e1c376934556.png)

**Comment by yongman** [comment]
does your tidis have supervised by supervisor? It will panic when all key not exists, a new commit https://github.com/yongman/tidis/commit/21ee8500c3f9141e221deb52ff0e7ab4e9417cad has been commited to fix it.

**Comment by jklofs** [comment]
感谢你的修复不过sunionstore/sdiffstore/sinterstore 依然有问题
![image](https://user-images.githubusercontent.com/24784965/53775441-8f31e200-3f2d-11e9-96e6-336b0929e7dc.png)

**Comment by jklofs** [comment]
感谢你的修复，但是sunionstore/sdiffstore/sinterstore 任然存在问题
![image](https://user-images.githubusercontent.com/24784965/53775519-da4bf500-3f2d-11e9-822a-4d8c4e92f24d.png)

**Comment by yongman** [comment]
Appreciate your continuous tests first.
Sorry. I missed fixing the store commands. A new commit https://github.com/yongman/tidis/commit/bb548301c637208d772c4d73ddfd3e7f248df972 has been commited.
