### ISSUE TITLE
sclear/zclear/ldel    bug

### ISSUE THREAD

**Issue by jklofs** [yongman/tidis#63]
sclear/zclear/ldel   在key对应的value为空时命令会阻塞

**Comment by yongman** [comment]
Can you post issue with example?

**Comment by jklofs** [comment]
![image](https://user-images.githubusercontent.com/24784965/53718135-5a724c00-3e95-11e9-82cb-72b8c83f64f9.png)
例如发送一个这个命令，可是dsd是空的，此时该命令是不会有响应的

**Comment by jklofs** [comment]
![image](https://user-images.githubusercontent.com/24784965/53718192-8261af80-3e95-11e9-90dc-1bfb1f9cd336.png)
达到等待时间后，会抛超时异常

**Comment by yongman** [comment]
I can not reproduce it in my develop environment. 
Can you try to restart client or tidis to checkout the reason?

**Comment by jklofs** [comment]
重启后该现象消失。该现象是在我压测删除后出现的，是否是因为线程僵死？

**Comment by yongman** [comment]
@jklofs I will try to reproduce this condition and figure it out.
