### ISSUE TITLE
tikv client connect

### ISSUE THREAD

**Issue by jklofs** [yongman/tidis#66]
如何配置tidis请求tikv的grpc 连接数，暂时发现tidis无法把cpu吃满，压测效果不佳

**Comment by yongman** [comment]
@jklofs You can increase the number of parallel client connections to tidis and test again.

**Comment by jklofs** [comment]
能否将此配置暴露，现在测试下来感觉tidis只能吃到3/4的cpu，就无法再提升了
![image](https://user-images.githubusercontent.com/24784965/54170422-9f0f7000-44b1-11e9-9c56-574dd20046d9.png)

**Comment by yongman** [comment]
@jklofs I think the bottleneck may have little relation with the number of grpc connection. It may be linux kernel process context switch? network bandwidth? vm cpu steal?NIC queue? 
or may be complicated.
