### ISSUE TITLE
incrby step, not 1

### ISSUE THREAD

**Issue by alex-hsl** [yongman/tidis#69]
https://github.com/yongman/tidis/blob/bb548301c637208d772c4d73ddfd3e7f248df972/server/command_string.go#L418

**Comment by yongman** [comment]
@alex-hsl Thanks for your review, or you can create a pull request.

**Comment by yongman** [comment]
@alex-hsl https://github.com/yongman/tidis/commit/0ce5a4d4a76efaee7274ce872de52d1c3e6840ab Already fixed.
