### ISSUE TITLE
Thank you for this software. When production ready?

### ISSUE THREAD

**Issue by hiqbn** [yongman/tidis#70]
1. When production ready? (at least pls mention if get/set , hget/hset , zlist etc are fully production ready etc)
2. multi/exec really transactional or just put there to be compatible with redis?

**Comment by yongman** [comment]
1. `tidis` has not been fully tested for production and it will be appreciated you can test in some use case.
2. multi/exec is really transactional.

**Comment by yongman** [comment]
@hiqbn I think the `redis` benchmark data is well known. `tidis` is based on distributed persistent key value store, so the comparison with `redis` is meaningless and no needed.

**Comment by hiqbn** [comment]
just trying to compare hardware specs and the results of the qps for each that's all. i would like to know how much difference one same hardware spec.

**Comment by sameor** [comment]
Hi, when does tidis can use in production environment ?

**Comment by yongman** [comment]
I am glad people from community can use and test tidis together and report issues.
