### ISSUE TITLE
Is it possible to make Nodejs client connect to Redis switch to Tidis without any change?

### ISSUE THREAD

**Issue by kaisatec** [yongman/tidis#77]
Is it possible to make Nodejs client connect to Redis switch to Tidis without any change?

I am using

https://github.com/NodeRedis/node-redis

Just  wonder  if I can

1.switch to tidis directly
or
2.change some code of node-redis
or
3.use official tidis nodejs client(if have)

Thanks

**Comment by yongman** [comment]
@kaisatec I am working on refactoring the api compatibility with redis api. 
For now, tidis have compatible protocal with redis, but some api commands not.

**Comment by yongman** [comment]
@kaisatec This is in progress in `new-key-encoding` branch

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
