### ISSUE TITLE
Encryption At Rest

### ISSUE THREAD

**Issue by rock59** [yongman/tidis#79]
Any plan to support Encryption At Rest?

**Comment by tmikaeld** [comment]
I would assume this would need to be on a lower level or even disk-level?

**Comment by rock59** [comment]
@tmikaeld TiKV supports Encryption at Rest . I guess Tidis needs some configurations.

https://github.com/tikv/tikv/issues/3680
https://docs.pingcap.com/tidb/stable/encryption-at-rest#tikv-encryption-at-rest

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
