### ISSUE TITLE
HSet Write conflict happens when 2 goroutine write one key at same time

### ISSUE THREAD

**Issue by coder-zhuyu** [yongman/tidis#86]
package main

import (
	"context"
	"sync"
	"time"

	"github.com/go-redis/redis/v8"
)

func NewRDB() *redis.Client {
	return redis.NewClient(&redis.Options{
		Addr:         "localhost:5379",
		PoolSize:     100,
		MinIdleConns: 50,
		ReadTimeout:  1 * time.Second,
	})
}

func main() {
	rdb := NewRDB()
	defer rdb.Close()

	ctx := context.Background()
	hKey := "f_1234"

	var wg sync.WaitGroup
	wg.Add(2)
	go func() {
		defer wg.Done()
		for i := 1; i < 100; i++ {
			if err := rdb.HSet(ctx, hKey, i, "v").Err(); err != nil {
				panic(err)
			}
		}
	}()
	go func() {
		defer wg.Done()
		for i := 100; i < 200; i++ {
			if err := rdb.HSet(ctx, hKey, i, "v").Err(); err != nil {
				panic(err)
			}
		}
	}()
	wg.Wait()
}

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
