### ISSUE TITLE
有支持spop、zremrangebyrank 这两个command的计划吗

### ISSUE THREAD

**Issue by alexKeleon** [yongman/tidis#87]
172.18.1.14:5379> SADD myset "one"
(integer) 1
172.18.1.14:5379> SMEMBERS myset
1) "one"
172.18.1.14:5379> SPOP myset
(error) ERR command error

172.18.1.14:5379> zadd testz 1 1 2 2
(integer) 2
172.18.1.14:5379> zrange testz 1 2
1) "2"
172.18.1.14:5379> zrange testz 0 2
1) "1"
2) "2"
172.18.1.14:5379> zremrangebyscore testz 1 2
(integer) 2
172.18.1.14:5379> zrange testz 0 2
(empty list or set)
172.18.1.14:5379> zrange testz 0 1
(empty list or set)
172.18.1.14:5379> zadd testz 1 1 2 2 3 3
(integer) 3
172.18.1.14:5379> zremrangebyrank testz 1 2
(error) ERR command error

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
