### ISSUE TITLE
Panic when SAdd on priviously Set key.

### ISSUE THREAD

**Issue by 1995parham** [yongman/tidis#88]
I created a normal key by `Set` and then `SAdd` on it, this cause nil reference panic which I think was caused by returning nil and no error 

https://github.com/yongman/tidis/blob/8da5613fe14cd93d4d16ccd8d522747c943c969c/tidis/t_set.go#L48

which cause panic on the following

https://github.com/yongman/tidis/blob/8da5613fe14cd93d4d16ccd8d522747c943c969c/tidis/t_set.go#L100

if you agree I can create a PR for this by checking the return value besides error.

**Comment by yongman** [comment]
PR is welcomed.

**Comment by 1995parham** [comment]
Thanks @yongman :raised_hands:
