### ISSUE TITLE
[Proposal] Any plan to use RawKV apis?

### ISSUE THREAD

**Issue by c4pt0r** [yongman/tidis#9]
TiKV provides atomic Get/Put/Scan/Delete APIs at RawAPI layer with a higher performance than Transactional API.
Maybe some scenarios people just want a high performance KV database with scan API (just like dynamoDB & HBase), using RawAPI in these scenarios seems a good idea.

**Comment by yongman** [comment]
Thanks for advise. 

RawKV api have better performance as I know, but much more work have to do to guarantee the multi-key operation atomic. 

For example, a list user key contains a list meta key and some list item keys each list field,  and these raw key may be distributed in different regions,  just use rawkv api can not guarantee the correctness, right?

In first stage most work will be  implementation of most function features, and performance will be worked in next stage.

`first make it work, then make it right, then make it faster.`

I will study the rawkv api in deep for future work and I am happy getting official suggestions.

**Comment by c4pt0r** [comment]
Fair enough.

**Comment by ddorian** [comment]
@yongman 
In the "then make it faster", do you also mean implementing coprocessors in rust inside tikv ?

**Comment by yongman** [comment]
@ddorian most operations in tidis will be involving less than a few keys, and the data will be likely located in the same region, I think `coprocessors` will not helps a lot.
