### ISSUE TITLE
感谢，请问一下是否支持 PIPELINE写入

### ISSUE THREAD

**Issue by hangzhouminghe88** [yongman/tidis#91]
感谢，请问一下是否支持 PIPELINE写入

我用了 TIDIS + PD + TIKV , 发现写入会错误；SST文件生成有时候，有时候没有；

**Comment by yongman** [comment]
> 感谢，请问一下是否支持 PIPELINE写入
> 
> 我用了 TIDIS + PD + TIKV , 发现写入会错误；SST文件生成有时候，有时候没有；

支持PIPELINE，关于写入错误希望能说明详细一点，包括日志信息

**Comment by yongman** [comment]
Please refer to https://github.com/tidb-incubator/tidis
