### ISSUE TITLE
Write conflict

### ISSUE THREAD

**Issue by yybmsrs** [yongman/tidis#93]
`[[kv:9007]Write conflict, txnStartTS=431225910331965482, conflictStartTS=431225910449930345, conflictCommitTS=431225910449930356, key=[]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe, 0x64 } primary=[]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe, 0x64} [try again later]]`

20 go routines write concurrently, many errors as show

**Comment by yongman** [comment]
@yybmsrs tidis use optimistic transaction for data conflict. If a few writes to the same key at the same time,  conflict error will be generated then back-off retry.
